### ISSUE TITLE
Data and evaluation protocol don't match the paper

### ISSUE THREAD

**Issue by Daniela-Shereen** [yuh-yang/MBHT-KDD22#3]
The number of users and items in the datasets doesn't match the numbers mentioned in the paper. For example the Retailrocket, the number of users is 30691, while in the paper, it is 11649. Also, the evaluation protocol in the code is a ratio-based split (RS), while in the paper, it is the leave-one-out protocol can you please clarify?

**Comment by yuh-yang** [comment]
Hi, we generate training and testing data following the leave-one-out strategy, and specify the pre-processed files in `benchmark_filename`. Please note that in the RecBole framework, when `benchmark_filename` are defined, the dataset splitting protocols in the code, e.g., RS, are then disabled.

**Comment by yuh-yang** [comment]
As for the inconsistency of the Retailrocket dataset, maybe it is because we upload the wrong version of dataset. We will check and fix the problem soon :).

**Comment by Daniela-Shereen** [comment]
Dear Authors, The Tmall dataset number of users still doesn't match the numbers indicated in the paper. The number of user ids is more the 400K in the uploaded files. Is there an explanation

**Comment by yuh-yang** [comment]
Hi, @Daniela-Shereen ! Sorry for the late reply. We closely re-checked the statistical results of our datasets and here are the explanations:

For the Tmall & Retailrocket dataset we uploaded, you can get a statistics as `The number of users: 437367` and
`The number of users: 30691 `  while running in Recbole. 

Actually, this is after the duplication pre-processing. That is, we duplicate user sequences with a length longer than 3 for 3 times to enrich the training data, which is a common practice. However, we mistakenly incremented the session_id during this strategy. But this does not affect the benchmark results at all, since the sequential models involve no roles of users and we have another version of datasets that are not duplicated for those graph-based models. In Table 1 in the paper, we report the number of actual users instead. Sorry for making this ambiguous.
